// CurrentAddress
export const UPDATE_CURRENT_ADDRESS = 'UPDATE_CURRENT_ADDRESS'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
//Initial Location Updates
export const INITIAL_LAT = 'INITIAL_LAT'
export const INITIAL_LNG = 'INITIAL_LNG'
export const INITIAL_REGION = 'INITIAL_REGION'

//Register
export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER'
export const UPDATE_PHONE_WITH_CODE = 'UPDATE_PHONE_WITH_CODE'
export const UPDATE_COUNTRY_CODE = 'UPDATE_COUNTRY_CODE'
export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL' 

//DriverRegister
export const UPDATE_DRIVER_PHONE_NUMBER = 'UPDATE_DRIVER_PHONE_NUMBER'
export const UPDATE_DRIVER_PHONE_WITH_CODE = 'UPDATE_DRIVER_PHONE_WITH_CODE'
export const UPDATE_DRIVER_COUNTRY_CODE = 'UPDATE_DRIVER_COUNTRY_CODE'
export const UPDATE_DRIVER_FIRST_NAME = 'UPDATE_DRIVER_FIRST_NAME'
export const UPDATE_DRIVER_LAST_NAME = 'UPDATE_DRIVER_LAST_NAME'
export const UPDATE_DRIVER_EMAIL = 'UPDATE_DRIVER_EMAIL' 
export const UPDATE_DRIVER_LICENCE_NUMBER = 'UPDATE_DRIVER_LICENCE_NUMBER' 
export const UPDATE_DRIVER_DATE_OF_BIRTH = 'UPDATE_DRIVER_DATE_OF_BIRTH' 

//Vehicle Details
export const UPDATE_VEHICLE_NAME = 'UPDATE_VEHICLE_NAME'
export const UPDATE_VEHICLE_BRAND = 'UPDATE_VEHICLE_BRAND'
export const UPDATE_VEHICLE_COLOR = 'UPDATE_VEHICLE_COLOR'
export const UPDATE_VEHICLE_NUMBER = 'UPDATE_VEHICLE_NUMBER'
export const UPDATE_VEHICLE_TYPE = 'UPDATE_VEHICLE_TYPE'
export const UPDATE_VEHICLE_TYPE_LBL = 'UPDATE_VEHICLE_TYPE_LBL'

//Paypal Status
export const PAYPAL_PAYMENT_STATUS = 'PAYPAL_PAYMENT_STATUS' 

//Stripe Status
export const STRIPE_PAYMENT_STATUS = 'STRIPE_PAYMENT_STATUS' 